# Generated by Django 4.2.5 on 2023-10-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_actors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_year',
            new_name='release_date',
        ),
    ]
